education_courses/account/urls.py
from django. urls import path

from account.views import login, signup, profile

app_name = 'account'

urlpatterns = [
    path('login/', login.login_view, name='login'),
    path('signup/', signup.signup, name='signup'),
    path('profile/', profile.profile, name='profile'),
    path('logout/', profile.LogoutView.as_view(), name='logout'),
    path('profile/update/', profile.update_profile, name='profile_update')
]

education_courses/courses/urls.py
from django. urls import path

from courses.views import courses

app_name = 'courses'

urlpatterns = [
    path('all/', courses.courses_all, name='courses-all'),
    path('course/delete/<uuid:uid>/', courses.course_delete, name='courses-delete'),
    path('course/search/<str:course_name>/<str:select_course>/', courses.courses_search, name='courses-search'),
    path('course/<uuid:uid>/', courses.course_detail, name='courses-detail'),
    path('course/order/', courses.course_order, name='courses-order'),
]

education_courses/education_courses/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing.urls')),
    path('', include('account.urls')),
    path('courses/', include('courses.urls')),
]

education_courses/landing/urls.py
from django. urls import path

from landing.views import landing

app_name = 'landing'

urlpatterns = [
    path('', landing.index, name='index'),
]

education_courses/courses/models.py
from django.db import models
from account.models import Account
import uuid
from django.utils.translation import gettext_lazy as _


class Directions(models.Model):
    IT_TECH = 'Информационные технологии'
    MARKETING = 'Маркетинг'
    DESIGN = 'Дизайн'


    PROGRAM_LANG = [
        (IT_TECH, _('Информационные технологиий')),
        (MARKETING, _('Маркетинг')),
        (DESIGN, _('Дизайн')),
    ]

    name = models.CharField(_("Языки программирования"), choices=PROGRAM_LANG, max_length=50)
    image = models.ImageField(_("Изображение"), upload_to='static/img/directions_images/')

    def __str__(self):
        return self.name

class Devices(models.Model):
    DESKTOP = 'Десктоп'
    WEB = 'Веб'
    MOBILE = 'Mobile'
    ITEMS = 'Оборудование'
    SMART_ITEMS = 'Умные устройства'


    PROGRAM_LANG = [
        (DESKTOP, _('Десктоп')),
        (WEB, _('Веб')),
        (MOBILE, _('Mobile')),
        (ITEMS, _('Оборудование')),
        (SMART_ITEMS, _('Умные устройства')),
    ]

    name = models.CharField(_("Языки программирования"), choices=PROGRAM_LANG, max_length=50)

    def __str__(self):
        return self.name


class Program(models.Model):
    BASE = 'Базовый'


    PROGRAM_LANG = [
        (BASE, _('Базовый')),
    ]

    name = models.CharField(_("Языки программирования"), choices=PROGRAM_LANG, max_length=50)

    def __str__(self):
        return self.name

class Special(models.Model):
    JUNIOR = 'Junior'
    MIDDLE = 'Middle'
    MIDDLE_PLUS = 'Middle+'

    PROGRAM_LANG = [
        (JUNIOR, _('Junior')),
        (MIDDLE, _('Middle')),
        (MIDDLE_PLUS, _('Middle+')),
    ]

    name = models.CharField(_("Языки программирования"), choices=PROGRAM_LANG, max_length=50)

    def __str__(self):
        return self.name
    
class Package(models.Model):
    BASE = 'Базовый'
    MASTER = 'Мастер'
    PRO = 'Про'

    PROGRAM_PACKAGE = [
        (BASE, _('Базовый')),
        (MASTER, _('Мастер')),
        (PRO, _('Про')),
    ]

    
    DIPLOM_1 = 'В конце обучения'
    DIPLOM_2 = '12 месяцев'

    DIPLOMS = [
        (DIPLOM_1 , _('В конце обучения')),
        (DIPLOM_2, _('12 месяцев')),
    ]

    TIME_1 = '12 месяцев'
    TIME_2 = '24 месяцев'
    TIME_3 = '36 месяцев'

    TIMES = [
        (TIME_1 , _('12 месяцев')),
        (TIME_2, _('24 месяцев')),
        (TIME_3, _('36 месяцев')),
    ]

    PRICE_1 = '3510'
    PRICE_2 = '4052'
    PRICE_3 = '5921'

    PRICES = [
        (PRICE_1 , _('3510')),
        (PRICE_2, _('4052')),
        (PRICE_3, _('5921')),
    ]

    name = models.CharField(_("Пакет"), choices=PROGRAM_PACKAGE, max_length=50)
    level = models.ForeignKey(Special, verbose_name=_("Знания на выходе"), on_delete=models.CASCADE, null=True)
    diplom = models.CharField(_("Пакет"), choices=DIPLOMS, max_length=90, null=True)
    time = models.CharField(_("Срок обучения"), choices=TIMES, max_length=90, null=True)
    price = models.CharField(_("Цена в месяц"), choices=PRICES, max_length=90, null=True)

    def __str__(self):
        return self.name
    
class Temp(models.Model):
    STANDART = 'Стандартный'
    INTENSIVE = 'Интенсивный'
    SLOW = 'Замедленный'

    PROGRAM_TEMP = [
        (STANDART, _('Стандартный')),
        (INTENSIVE, _('Интенсивный')),
        (SLOW, _('Замедленный')),
    ]

    PRICE_1 = 'Бесплатно'
    PRICE_2 = '1621'

    PRICES = [
        (PRICE_1, _('Бесплатно')),
        (PRICE_2, _('1621'))
    ]

    name = models.CharField(_("Темп"), choices=PROGRAM_TEMP, max_length=50)
    price = models.CharField(_("Цена в месяц"), choices=PRICES, max_length=90, null=True)

    def __str__(self):
        return self.name
    

class Option(models.Model):
    INDIVID = 'Индивидуальные занятия'
    DIPLOM = 'Диплом установленного образца'
    GARANT = 'Гарантия трудоустройства'
    PROF = 'Профориентация'

    PROGRAM_OPTION = [
        (INDIVID, _('Индивидуальные занятия')),
        (DIPLOM, _('Диплом установленного образца')),
        (GARANT, _('Гарантия трудоустройства')),
        (PROF, _('Профориентация'))
    ]

    PRICE_1 = '12500'
    PRICE_2 = '30000'
    PRICE_3 = '25000'

    PRICES = [
        (PRICE_1, _('12500')),
        (PRICE_2, _('30000')),
        (PRICE_3, _('25000'))
    ]

    name = models.CharField(_("Опция"), choices=PROGRAM_OPTION, max_length=150)
    price = models.CharField(_("Цена в месяц"), choices=PRICES, max_length=90, null=True)

    def __str__(self):
        return self.name

class LangueProg(models.Model):
    C_PLUS = 'C++'
    C_SHARP = 'C#'
    PYTHON = 'Python'
    JAVA = 'Java'
    JAVA_SCRIPT = 'JavaScript'

    PROGRAM_LANG = [
        (C_PLUS, _('C++')),
        (C_SHARP, _('C#')),
        (PYTHON, _('Python')),
        (JAVA, _('Java')),
        (JAVA_SCRIPT, _('JavaScript')),
    ]

    name = models.CharField(_("Языки программирования"), choices=PROGRAM_LANG, max_length=50)

    def __str__(self):
        return self.name
    
class Target(models.Model):
    name = models.CharField(_("Цели"), max_length=90)

    def __str__(self):
        return self.name
    

class TypeEducation(models.Model):
    name = models.CharField(_("Тип обучения"), max_length=90)
    description = models.TextField(_("Описание"))

    def __str__(self):
        return self.name

class Course(models.Model):
    uid = models.UUIDField(unique=True, editable=False, default=uuid.uuid4)
    lang = models.ManyToManyField(LangueProg, verbose_name=_("Языки Программирования"))
    title = models.CharField(_("Название курса"), max_length=90)
    description = models.TextField(_("Описание"))
    cost = models.IntegerField(_("Цена"))
    directions = models.ForeignKey(Directions, verbose_name=_("Направления"), on_delete=models.CASCADE, null=True)
    device = models.ForeignKey(Devices, verbose_name=_("Устройства"), on_delete=models.CASCADE, null=True)
    special = models.ForeignKey(Special, verbose_name=_("Уровень"), on_delete=models.CASCADE, null=True)


class Order(models.Model):
    uid = models.UUIDField(unique=True, editable=False, default=uuid.uuid4)
    user = models.ForeignKey(Account, verbose_name=_("Пользователь"), on_delete=models.CASCADE, null=False)
    directions = models.ForeignKey(Directions, verbose_name=_("Направления"), on_delete=models.CASCADE, null=True)
    package = models.ForeignKey(Package, verbose_name=_("Пакет"), on_delete=models.CASCADE, null=True)
    temp = models.ForeignKey(Temp, verbose_name=_("Темп обучения"), on_delete=models.CASCADE, null=True)
    name = models.CharField(_("Имя фамилия"), max_length=250)
    email = models.CharField(_("Email"), max_length=15)
    type_education = models.ForeignKey(TypeEducation, verbose_name=_("Тип обучения"), on_delete=models.CASCADE, null=True)
    option = models.ManyToManyField(Option, verbose_name=_("Опции"))
    target = models.ManyToManyField(Target, verbose_name=_("Цели"))
    phone_number = models.CharField(max_length=13, unique=True)
    value = models.FloatField(_("Сумма"), null=True)

    def save(self, *args, **kwargs):
        # Проверка и обработка номера телефона перед сохранением
        if not self.phone_number.startswith('+7'):
            self.phone_number = '+7' + self.phone_number[-10:]
        super().save(*args, **kwargs)

education_courses/courses/views.py
from django.shortcuts import render

# Create your views here.

education_courses/courses/views/courses.py
from django.shortcuts import render, redirect
from courses.models import Course, Order, Directions, TypeEducation, Temp, Option, Package, Target
import uuid
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.http import JsonResponse


def courses_search(request, course_name=None, select_course=None ):
    template = 'courses/courses.html'

    if request.method == 'POST':
            selected_specials = request.POST.getlist('special')
            selected_directions = request.POST.getlist('directions')
            selected_devices = request.POST.getlist('devices')
            search_query = request.POST.get('search')
    else:
        selected_specials = []
        selected_devices = []
        selected_directions = []
        search_query = None

    courses = Course.objects.all()
    print("select_course", select_course)
    if selected_devices:
        courses = courses.filter(device__name__in=selected_devices)
    if selected_directions:
        courses = courses.filter(directions__name__in=selected_directions)
    if selected_specials:
        courses = courses.filter(special__name__in=selected_specials)
    if search_query:
        courses = courses.filter(title__icontains=search_query)
    if course_name:
        courses = Course.objects.filter(title=course_name)
    if select_course is not None or course_name == None:
        courses = Course.objects.filter(directions=select_course)
    else:
        courses = Course.objects.all()
         
    context = {'courses': courses, 'course_name':course_name, 'select_course':select_course}
    return render(request, template, context)


def courses_all(request):
    template = 'courses/courses.html'
    # Получение отправленных данных из запроса
    if request.method == 'POST':
            selected_specials = request.POST.getlist('special')
            selected_directions = request.POST.getlist('directions')
            selected_devices = request.POST.getlist('devices')
            search_query = request.POST.get('search')
    else:
        selected_specials = []
        selected_devices = []
        selected_directions = []
        search_query = None

    courses = Course.objects.all()
    if selected_devices:
         courses = courses.filter(device__name__in=selected_devices)
    if selected_directions:
         courses = courses.filter(directions__name__in=selected_directions)
    if selected_specials:
            courses = courses.filter(special__name__in=selected_specials)
    if search_query:
        courses = courses.filter(title__icontains=search_query)
    context = {'courses': courses }
    return render(request, template, context)


def course_detail(request, uid):
    course = get_object_or_404(Course, uid=uid)
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        phone_number = request.POST.get('phone_number')
        value_main = request.POST.get('value_main')

        order = Order(
                user = request.user,
                directions=course.directions,
                name=name,
                email=email,
                phone_number=phone_number,
                value=value_main
            )
        order.save()
        return redirect('account:profile')
    
    template = 'courses/course_detail.html'
    context = {'course': course}
    return render(request, template, context)


def course_order(request):
    if request.method == 'POST':
        directions_ids = request.POST.getlist('directions')
        typeEducation = request.POST.getlist('typeEducation')
        package_ids = request.POST.getlist('package')
        temp_id = request.POST.getlist('temp')
        name = request.POST.get('name')
        email = request.POST.get('email')
        option_ids = request.POST.getlist('option')
        phone_number = request.POST.get('phone_number')
        targets_ids = request.POST.getlist('target')
        value = request.POST.get('value_all_total')

        directions = Directions.objects.filter(id__in=directions_ids)
        education = TypeEducation.objects.filter(id__in=typeEducation)
        targets_f = Target.objects.filter(id__in=targets_ids)
        package = Package.objects.filter(id__in=package_ids)
        temp = Temp.objects.filter(id__in=temp_id)
        option = Option.objects.filter(id__in=option_ids)



        order = Order(
            user=request.user,
            directions=directions.first(),
            package=package.first(),
            temp=temp.first(),
            name=name,
            email=email,
            type_education=education.first(),
            phone_number=phone_number,
            value=value
            )
        order.save()
        order.target.set(targets_f)
        order.option.set(option)
        return redirect('account:profile')

    directions = Directions.objects.all()
    options = Option.objects.all()
    temps = Temp.objects.all()
    targets = Target.objects.all()
    typeEducation = TypeEducation.objects.all()
    package = Package.objects.all()

    template = 'courses/course_order.html'
    context = {'directions':directions, 'typeEducation':typeEducation, 'options': options, 'temps': temps, 'packages': package, 'targets': targets}
    return render(request, template, context)


def course_delete(request, uid):
    print(uid)
    try:
        course = Order.objects.get(uid=uid)
        course.delete()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    except Order.DoesNotExist:
        return JsonResponse({'success': False, 'message': 'Course not found'})
    except Exception as e:
        return JsonResponse({'success': False, 'message': str(e)})

education_courses/courses/templates/courses/courses.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <title>Все программы обучения</title>
</head>
<body>
    <header class="header__courses">
        <div class="header__courses__top">
          <div class="container">
            <div class="header__top-row">
              <a>
                <h3>Education Courses</h3>
            </a>
            <div class="header__nav">
                <nav class="nav">
                    <ul class="nav__list">
                        <li><a href="{% url 'landing:index' %}">Главная</a></li>
                        <li><a href="#!">Контакты</a></li>
                        <li><a href="#!">Отзывы</a></li>
                        <li><a href="#!">Подписаться</a></li>
                    </ul>
                </nav>
            </div>
            <div class="header__nav">
                <nav class="nav">
                    <ul class="nav__list">
                        {% if request.user %}
                        <li><a class="orange" href="{% url 'account:profile' %}">{{ request.user.email }}</a></li>
                        {% else %}
                        <li><a class="button orange" href="{% url 'account:login' %}">Войти</a></li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
            </div>
          </div>
        </div>    
    </header>
    <div class="courses__title">
        <div class="container">
            <h1>Все программы обучения</h1>
            <div class="courses__title-list">
                <div class="course__tag">
                    Все направления
                </div>
                <div class="course__tag">
                    ИТ
                </div>
                <div class="course__tag">
                    Программирование
                </div>
                <div class="course__tag">
                    Машинное обучение
                </div>
                <div class="course__tag">
                    Аналитика
                </div>
                <div class="course__tag">
                    Дизайн
                </div>
                <div class="course__tag">
                    Маркетинг
                </div>
                <div class="course__tag">
                    Blockchain
                </div>
            </div>
        </div>
    </div>
    <div class="courses__body__page">
        <div class="container">
        <div class="courses__body__page-left">
            <div class="filter__box">
                <h1>Поиск по программам</h1>
                <form method="POST" action="{% url 'courses:courses-all' %}">
                    {% csrf_token %}
                    <input class="search" name="search" type="text" placeholder="Поиск">
                    <button class="button orange" type="submit">Поиск</button>
            </div>
            <div class="filter__box">
                <h1>Направления</h1>
                    <div class="checkbox__input">
                        <input type="checkbox" id="directionsIT" value="Информационные технологии" name="directions">
                        <label for="scales">Информационные технологии</label>
                    </div>
                    <div class="checkbox__input">
                        <input type="checkbox" id="directionsMarket" value="Маркетинг" name="directions">
                        <label for="scales">Маркетинг</label>
                    </div>
                    <div class="checkbox__input">
                        <input type="checkbox" id="directionsDesign" value="Дизайн" name="directions">
                        <label for="scales">Дизайн</label>
                    </div>
                    <button class="button orange" type="submit">Поиск</button>
            </div>
            <div class="filter__box">
                <h1>Знания на выходе</h1>
                    <div class="checkbox__input">
                        <input type="checkbox" id="f_junior" value="junior" name='special'>
                        <label for="f_junior">Junior</label>
                    </div>
                    <div class="checkbox__input">
                        <input type="checkbox" id="f_middle" value="middle" name='special'>
                        <label for="f_middle">Middle</label>
                    </div>
                    <div class="checkbox__input">
                        <input type="checkbox" id="f_middle_plus" value="middle+" name='special'>
                        <label for="f_middle_plus">Middle+</label>
                    </div>
                    <button class="button orange" type="submit">Поиск</button>
            </div>
            <div class="filter__box">
                <h1>Устройства</h1>
                    <div class="checkbox__input">
                        <input type="checkbox" id="devicesDesk" value='Десктоп' name="devices">
                        <label for="scales">Десктоп</label>
                    </div>
                    <div class="checkbox__input">
                        <input type="checkbox" id="devicesWeb" value='Веб'  name="devices">
                        <label for="scales">Веб</label>
                    </div>
                    <div class="checkbox__input">
                        <input type="checkbox" id="devicesMobile" value='Mobile' name="devices">
                        <label for="scales">Mobile</label>
                    </div>
                    <div class="checkbox__input">
                        <input type="checkbox" id="devicesItems" value='Оборудование' name="devices">
                        <label for="scales">Оборудование</label>
                    </div>
                    <div class="checkbox__input">
                        <input type="checkbox" id="devicesSmart" value='Умные устройства' name="devices">
                        <label for="scales">Умные устройства</label>
                    </div>
                    <button class="button orange" type="submit">Поиск</button>
            </div>
            <div class="filter__box">
                <h1>Цель знание</h1>
                    <div class="checkbox__input">
                    <input type="checkbox" id="scales" name="scales">
                    <label for="scales">Образование</label>
                </div>
                <div class="checkbox__input">
                    <input type="checkbox" id="scales" name="scales">
                    <label for="scales">Повышение квалификации</label>
                </div>
                <div class="checkbox__input">
                    <input type="checkbox" id="scales" name="scales">
                    <label for="scales">Увеличить знания по теме</label>
                </div>
                <button class="button orange" type="submit">Поиск</button>
                </form>
            </div>
        </div>
        <div class="courses__body__page-right">
            {% for course in courses %}
            <div class="course__block">
                <h1>{{ course.title }}</h1>
                <p>{{ course.description }}</p>
                <div class="course__block-row">
                    {% for language in course.lang.all %}
                    <div class="element__course">
                        <span>{{ language.name }}</span>
                    </div>
                    {% endfor %}
                </div>
                <div class="line-width"></div>
                <a href="{% url 'courses:courses-detail' course.uid %}" class="button orange">Подробнее</a>
            </div>
            {% endfor %}
        </div>
    </div>
    </div>
</body>
</html>