education_courses/account/urls.py
from django. urls import path

from account.views import login, signup, profile

app_name = 'account'

urlpatterns = [
    path('login/', login.login_view, name='login'),
    path('signup/', signup.signup, name='signup'),
    path('profile/', profile.profile, name='profile'),
    path('logout/', profile.LogoutView.as_view(), name='logout'),
    path('profile/update/', profile.update_profile, name='profile_update')
]

education_courses/courses/urls.py
from django. urls import path

from courses.views import courses

app_name = 'courses'

urlpatterns = [
    path('all/', courses.courses_all, name='courses-all'),
    path('course/delete/<uuid:uid>/', courses.course_delete, name='courses-delete'),
    path('course/search/<str:course_name>/<str:select_course>/', courses.courses_search, name='courses-search'),
    path('course/<uuid:uid>/', courses.course_detail, name='courses-detail'),
    path('course/order/', courses.course_order, name='courses-order'),
]

education_courses/education_courses/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing.urls')),
    path('', include('account.urls')),
    path('courses/', include('courses.urls')),
]

education_courses/landing/urls.py
from django. urls import path

from landing.views import landing

app_name = 'landing'

urlpatterns = [
    path('', landing.index, name='index'),
]

education_courses/landing/models.py
from django.db import models

# Create your models here.

education_courses/courses/views/courses.py
from django.shortcuts import render, redirect
from courses.models import Course, Order, Directions, TypeEducation, Temp, Option, Package, Target
import uuid
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.http import JsonResponse


def courses_search(request, course_name=None, select_course=None ):
    template = 'courses/courses.html'

    if request.method == 'POST':
            selected_specials = request.POST.getlist('special')
            selected_directions = request.POST.getlist('directions')
            selected_devices = request.POST.getlist('devices')
            search_query = request.POST.get('search')
    else:
        selected_specials = []
        selected_devices = []
        selected_directions = []
        search_query = None

    courses = Course.objects.all()
    print("select_course", select_course)
    if selected_devices:
        courses = courses.filter(device__name__in=selected_devices)
    if selected_directions:
        courses = courses.filter(directions__name__in=selected_directions)
    if selected_specials:
        courses = courses.filter(special__name__in=selected_specials)
    if search_query:
        courses = courses.filter(title__icontains=search_query)
    if course_name:
        courses = Course.objects.filter(title=course_name)
    if select_course is not None or course_name == None:
        courses = Course.objects.filter(directions=select_course)
    else:
        courses = Course.objects.all()
         
    context = {'courses': courses, 'course_name':course_name, 'select_course':select_course}
    return render(request, template, context)


def courses_all(request):
    template = 'courses/courses.html'
    # Получение отправленных данных из запроса
    if request.method == 'POST':
            selected_specials = request.POST.getlist('special')
            selected_directions = request.POST.getlist('directions')
            selected_devices = request.POST.getlist('devices')
            search_query = request.POST.get('search')
    else:
        selected_specials = []
        selected_devices = []
        selected_directions = []
        search_query = None

    courses = Course.objects.all()
    if selected_devices:
         courses = courses.filter(device__name__in=selected_devices)
    if selected_directions:
         courses = courses.filter(directions__name__in=selected_directions)
    if selected_specials:
            courses = courses.filter(special__name__in=selected_specials)
    if search_query:
        courses = courses.filter(title__icontains=search_query)
    context = {'courses': courses }
    return render(request, template, context)


def course_detail(request, uid):
    course = get_object_or_404(Course, uid=uid)
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        phone_number = request.POST.get('phone_number')
        value_main = request.POST.get('value_main')

        order = Order(
                user = request.user,
                directions=course.directions,
                name=name,
                email=email,
                phone_number=phone_number,
                value=value_main
            )
        order.save()
        return redirect('account:profile')
    
    template = 'courses/course_detail.html'
    context = {'course': course}
    return render(request, template, context)


def course_order(request):
    if request.method == 'POST':
        directions_ids = request.POST.getlist('directions')
        typeEducation = request.POST.getlist('typeEducation')
        package_ids = request.POST.getlist('package')
        temp_id = request.POST.getlist('temp')
        name = request.POST.get('name')
        email = request.POST.get('email')
        option_ids = request.POST.getlist('option')
        phone_number = request.POST.get('phone_number')
        targets_ids = request.POST.getlist('target')
        value = request.POST.get('value_all_total')

        directions = Directions.objects.filter(id__in=directions_ids)
        education = TypeEducation.objects.filter(id__in=typeEducation)
        targets_f = Target.objects.filter(id__in=targets_ids)
        package = Package.objects.filter(id__in=package_ids)
        temp = Temp.objects.filter(id__in=temp_id)
        option = Option.objects.filter(id__in=option_ids)



        order = Order(
            user=request.user,
            directions=directions.first(),
            package=package.first(),
            temp=temp.first(),
            name=name,
            email=email,
            type_education=education.first(),
            phone_number=phone_number,
            value=value
            )
        order.save()
        order.target.set(targets_f)
        order.option.set(option)
        return redirect('account:profile')

    directions = Directions.objects.all()
    options = Option.objects.all()
    temps = Temp.objects.all()
    targets = Target.objects.all()
    typeEducation = TypeEducation.objects.all()
    package = Package.objects.all()

    template = 'courses/course_order.html'
    context = {'directions':directions, 'typeEducation':typeEducation, 'options': options, 'temps': temps, 'packages': package, 'targets': targets}
    return render(request, template, context)


def course_delete(request, uid):
    print(uid)
    try:
        course = Order.objects.get(uid=uid)
        course.delete()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    except Order.DoesNotExist:
        return JsonResponse({'success': False, 'message': 'Course not found'})
    except Exception as e:
        return JsonResponse({'success': False, 'message': str(e)})

education_courses/landing/views.py
from django.shortcuts import render

# Create your views here.

education_courses/landing/views/landing.py
from django.shortcuts import render, redirect
from courses.models import Directions


def index(request):
    template = 'landing/app.html'

    directions = Directions.objects.all()
    if request.method == 'POST':
        course_name = request.POST.get('course_name')
        select_course = request.POST.get('select_course')
        if course_name and select_course:
            # Оба значения переданы, перенаправляем на другой метод с двумя параметрами
            return redirect('courses:courses-search', course_name=course_name, select_course=select_course)
        elif course_name:
            # Передано только значение course_name
            return redirect('courses:courses-search', course_name=course_name, select_course=None)
        elif select_course:
            # Передано только значение select_course
            return redirect('courses:courses-search', course_name=None, select_course=select_course)
        else:
            # Не передано ни одно значение
            return redirect('courses:courses-search', course_name=None, select_course=None)
    context = {
    'request': request,
    'directions': directions
    }
    return render(request, template, context)

education_courses/landing/templates/landing/blocks/breefs.html
<div class="breefs__body">
    <div class="container">
        <div class="breefs__left">
            <h1>Отличные предложения <br> для Вас</h1>
        </div>
        <div class="breefs__right">
            <div class="breefs__right-row">
                <div class="breefs__element">
                    <div class="circle__decoration">
                        <svg width="31" height="31" viewBox="0 0 68 68" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <g id="iconspace_Bill Copy_25px">
                            <path id="path" fill-rule="evenodd" clip-rule="evenodd" d="M17.68 62.5612H19.7645L20.9363 60.2958C21.4978 59.2102 21.76 58.1853 21.76 57.1778C21.76 56.1483 21.486 55.0833 20.8978 53.9415L18.332 48.9612H54.4V6.80118C54.4 5.85082 53.4501 5.19351 52.5607 5.52843L42.2254 9.42052L31.754 5.52647C31.4435 5.41097 31.1014 5.41283 30.7921 5.5317L20.59 9.45243L9.99251 5.5259C9.10424 5.19678 8.16 5.85389 8.16 6.80118V53.0412C8.16 58.2989 12.4223 62.5612 17.68 62.5612ZM20.4 21.7599H31.28C32.0311 21.7599 32.64 22.3688 32.64 23.1199C32.64 23.871 32.0311 24.4799 31.28 24.4799H20.4C19.6489 24.4799 19.04 23.871 19.04 23.1199C19.04 22.3688 19.6489 21.7599 20.4 21.7599ZM20.4 32.6399C19.6489 32.6399 19.04 33.2488 19.04 33.9999C19.04 34.751 19.6489 35.3599 20.4 35.3599H42.16C42.9111 35.3599 43.52 34.751 43.52 33.9999C43.52 33.2488 42.9111 32.6399 42.16 32.6399H20.4ZM63.976 58.4787C63.976 54.7669 61.0021 51.7498 57.307 51.6799H21.76C23.9917 53.9132 25.1836 56.1806 25.188 58.5271C25.1924 60.8728 24.0097 63.1072 21.7868 65.2787H57.176C60.9315 65.2787 63.976 62.2342 63.976 58.4787Z" fill="#FF8700"/>
                            </g>
                            </svg>                            
                    </div>
                    <h1>Простая оплата</h1>
                    <p>Онлайн, выставление счетов-фактур и контрактов</p>
                </div>
                <div class="breefs__element">
                    <div class="circle__decoration">
                        <svg width="31" height="31" viewBox="0 0 68 68" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <g id="iconspace_Select Tab_25px">
                            <path id="Path" fill-rule="evenodd" clip-rule="evenodd" d="M62.56 21.7599H5.44V9.51994C5.44 7.26662 7.26668 5.43994 9.52 5.43994H58.48C60.7333 5.43994 62.56 7.26662 62.56 9.51994V21.7599ZM19.04 13.5999C19.04 15.1022 17.8222 16.3199 16.32 16.3199C14.8178 16.3199 13.6 15.1022 13.6 13.5999C13.6 12.0977 14.8178 10.8799 16.32 10.8799C17.8222 10.8799 19.04 12.0977 19.04 13.5999ZM24.48 16.3199C25.9822 16.3199 27.2 15.1022 27.2 13.5999C27.2 12.0977 25.9822 10.8799 24.48 10.8799C22.9778 10.8799 21.76 12.0977 21.76 13.5999C21.76 15.1022 22.9778 16.3199 24.48 16.3199Z" fill="#FF8700"/>
                            <path id="Path_2" fill-rule="evenodd" clip-rule="evenodd" d="M62.56 53.04V24.48H5.44V53.04C5.44 58.2977 9.70225 62.56 14.96 62.56H53.04C58.2978 62.56 62.56 58.2977 62.56 53.04ZM43.1157 35.7524C42.5813 35.2246 41.7202 35.2299 41.1924 35.7643L31.3985 45.6801L26.7923 41.1621C26.2561 40.6361 25.395 40.6445 24.8691 41.1807C24.3431 41.7169 24.3515 42.578 24.8877 43.1039L30.4614 48.5709C30.9963 49.0956 31.8548 49.0888 32.3813 48.5557L43.1276 37.6757C43.6554 37.1413 43.6501 36.2802 43.1157 35.7524Z" fill="#FF8700"/>
                            </g>
                            </svg>
                                                      
                    </div>
                    <h1>Планирование</h1>
                    <p>Простое планирование и отслеживание посещаемости</p>
                </div>
                <div class="breefs__element">
                    <div class="circle__decoration">
                        <svg width="31" height="31" viewBox="0 0 68 68" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <g id="iconspace_Board_25px">
                            <path id="Path" fill-rule="evenodd" clip-rule="evenodd" d="M57.12 20.3999C57.12 15.5746 53.5301 11.5878 48.8753 10.9646C48.9312 11.3818 48.96 11.8075 48.96 12.2399C48.96 17.4977 44.6978 21.7599 39.44 21.7599H28.56C23.3023 21.7599 19.04 17.4977 19.04 12.2399C19.04 11.8075 19.0688 11.3818 19.1247 10.9646C14.47 11.5878 10.88 15.5746 10.88 20.3999V53.0399C10.88 58.2977 15.1423 62.5599 20.4 62.5599H47.6C52.8578 62.5599 57.12 58.2977 57.12 53.0399V20.3999ZM44.88 40.7999H23.12C22.3689 40.7999 21.76 40.191 21.76 39.4399C21.76 38.6888 22.3689 38.0799 23.12 38.0799H44.88C45.6311 38.0799 46.24 38.6888 46.24 39.4399C46.24 40.191 45.6311 40.7999 44.88 40.7999ZM23.12 29.9199H44.88C45.6311 29.9199 46.24 29.311 46.24 28.5599C46.24 27.8088 45.6311 27.1999 44.88 27.1999H23.12C22.3689 27.1999 21.76 27.8088 21.76 28.5599C21.76 29.311 22.3689 29.9199 23.12 29.9199ZM44.88 51.6799H23.12C22.3689 51.6799 21.76 51.071 21.76 50.3199C21.76 49.5688 22.3689 48.9599 23.12 48.9599H44.88C45.6311 48.9599 46.24 49.5688 46.24 50.3199C46.24 51.071 45.6311 51.6799 44.88 51.6799Z" fill="#FF8700"/>
                            <path id="Path_2" d="M28.56 5.43994H39.44C43.1955 5.43994 46.24 8.48441 46.24 12.2399C46.24 15.9955 43.1955 19.0399 39.44 19.0399H28.56C24.8045 19.0399 21.76 15.9955 21.76 12.2399C21.76 8.48441 24.8045 5.43994 28.56 5.43994Z" fill="#FF8700"/>
                            </g>
                            </svg>
                                                       
                    </div>
                    <h1>Отчет</h1>
                    <p>Отслеживание учащихся и хороший аналитический отчет</p>
                </div>
            </div>
        </div>
    </div>
</div>

education_courses/landing/templates/landing/blocks/comm.html
{% load static %}
<div class="comm__body">
    <div class="container">
        <div class="comm__space">
            <div class="comm__left">
                <h1>Комьюнити Колледж</h1>
                <p>
                    Онлайн-комьюнити Колледжа насчитывает 
                    несколько тысяч подписчиков. Колледж представляют официальные паблики и студенческие сообщества, каналы по интересам. Официально 
                    Колледж активно присутствует в самых популярных и крупных соцсетях:
                </p>
            </div>
            <div class="comm_right">
                <img src="{% static 'img/comm.png'%}" alt="">
            </div>
        </div>
    </div>
</div>

education_courses/landing/templates/landing/blocks/education.html
{% load static %}
<div class="education__body">
    <div class="container">
        <div class="education__left">
            <img src="{% static 'img/education.png'%}" alt="">
        </div>
        <div class="education__right">
            <h1>
                Качественное <br> образование,<br> поддерживающие <br> человеческие ресурсы
            </h1>
            <a class="button orange" href="{% url 'courses:courses-order' %}">Узнать больше</a>
        </div>
    </div>
</div>

education_courses/landing/templates/landing/blocks/footer.html
{% load static %}
<div class="footer">
    <div class="container">
        <div class="footer__left">
            <img src="{% static 'img/logo.png'%}" alt="">
        </div>

        <div class="footer__right">
            <div class="footer__column">
                <h1>Колледж</h1>
                <ul>
                    <li>
                        <a>
                            Документы
                        </a>
                    </li>
                    <li>
                        <a>
                            Ресурсы
                        </a>
                    </li>
                    <li>
                        <a>
                            ТОЦ Samsung
                        </a>
                    </li>
                    <li>
                        <a>
                            Новости
                        </a>
                    </li>
                </ul>
            </div>
            <div class="footer__column">
                <h1>Студенту</h1>
                <ul>
                    <li>
                        <a>
                            Расписание занятий
                        </a>
                    </li>
                    <li>
                        <a>
                            Библиотека
                        </a>
                    </li>
                    <li>
                        <a>
                            Дополнительное образование
                        </a>
                    </li>
                    <li>
                        <a>
                            Автошкола
                        </a>
                    </li>
                    <li>
                        <a>
                            Трудоустройство
                        </a>
                    </li>
                </ul>
            </div>
            <div class="footer__column">
                <h1>Сотруднику</h1>
                <ul>
                    <li>
                        <a>
                           АИС Колледж
                        </a>
                    </li>
                    <li>
                        <a>
                            Wiki Колледж
                        </a>
                    </li>
                    <li>
                        <a>
                            Moodle Колледж
                        </a>
                    </li>
                </ul>
            </div>
            <div class="footer__column">
                <h1>Подпишитесь</h1>
            </div>
        </div>
    </div>
</div>

education_courses/landing/templates/landing/blocks/headers.html
{% load static %}
<header class="header__landing">
    <div class="header__landing__top">
      <div class="container">
        <div class="header__top-row">
          <a>
            <h3>Education Courses</h3>
        </a>
        <div class="header__nav">
            <nav class="nav">
                <ul class="nav__list">
                    <li><a href="#!">Главная</a></li>
                    <li><a href="#!">Контакты</a></li>
                    <li><a href="#!">Отзывы</a></li>
                    <li><a href="#!">Подписаться</a></li>
                </ul>
            </nav>
        </div>
        <div class="header__nav">
            <nav class="nav">
                <ul class="nav__list">
                    {% if user.is_authenticated %}
                    <li><a class="orange" href="{% url 'account:profile' %}">{{ request.user.email }}</a></li>
                    {% else %}
                    <li><a class="button orange" href="{% url 'account:login' %}">Войти</a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
        </div>
      </div>
    </div>
  
    <div class="header__body">
      <div class="container">
        <div class="header_left">
            <div class="figure__decoration"></div>
        </div>
        <div class="header_right">
            <h1>Учитесь каждый день 
                любым новым навыкам онлайн с лучшими преподавателями.</h1>
                <form method="POST">
                    {% csrf_token %}
                <div class="header__search">
                    <div class="header__search-row">
                        <svg width="21" height="21" viewBox="0 0 50 50" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <g id="sea">
                            <path id="Path" fill-rule="evenodd" clip-rule="evenodd" d="M39.0605 38.9392L33.9695 33.8496C39.0151 27.7336 38.6302 18.7099 32.9602 13.0398C26.907 6.98672 17.093 6.98672 11.0398 13.0398C4.98672 19.093 4.98672 28.907 11.0398 34.9602C16.7093 40.6296 25.732 41.0151 31.848 35.9708L36.9395 41.0608C38.3539 42.4748 40.4749 40.3532 39.0605 38.9392ZM13.1612 15.1612C18.0427 10.2796 25.9573 10.2796 30.8388 15.1612C35.7204 20.0427 35.7204 27.9573 30.8388 32.8388C25.9573 37.7204 18.0427 37.7204 13.1612 32.8388C8.27961 27.9573 8.27961 20.0427 13.1612 15.1612Z" fill="#778195"/>
                            </g>
                            </svg>
                            
                        <input name="course_name" placeholder="Вставьте название">
                        <span>|</span>
                        <select name="select_course">
                            {% for direction in directions %}
                                <option value="{{ direction.id }}">{{ direction }}</option>
                            {% endfor %}
                        </select>
                        <button>Искать</button>
                    </div>
                </div>
            </form>
            </div>
      </div>
    </div>
  
  </header>